players['team_name'] = np.select(
    [
        players['team_code']==1,
        players['team_code']==2,
        players['team_code']==3,
        players['team_code']==4,
        players['team_code']==6,
        players['team_code']==7,
        players['team_code']==8,
        players['team_code']==11,
        players['team_code']==13,
        players['team_code']==14,
        players['team_code']==20,
        players['team_code']==21,
        players['team_code']==31,
        players['team_code']==36,
        players['team_code']==39,
        players['team_code']==43,
        players['team_code']==45,
        players['team_code']==57,
        players['team_code']==90,
        players['team_code']==94
    ],
    [
        'Manchester United',
        'Leeds United',
        'Arsenal',
        'Newcastle',
        'Tottenham Hotspur',
        'Aston Villa',
        'Chelsea',
        'Everton',
        'Leicester City',
        'Liverpool',
        'Southampton',
        'West Ham United',
        'Crystal Palace',
        'Brighton and Hove Albion',
        'Wolverhampton',
        'Manchester City',
        'Norwich City',
        'Watford',
        'Burnley',
        'Brentford'
    ], 
    default='Unknown'
)